auto: true
server: true
permalink: none
baseurl: /blog
exclude:
- .gitignore
- README.md

prose:
  metadata: 
    _posts/articles: |
      published: false
      layout: article
      title: Your Post Title
      abstract: Short summary of your article.
      author_twitter: kunstkernewek
      author: Oliver Scott
      categories:
      - articles  
    _posts/releases: |
      published: false
      layout: release
      headline: Briefly summarize the news - not title
      introduction: first paragraph - basic answers to who what when where why
      boilerplate: short "about" section - providing independent background on the issuing company/organization/individual
      author_twitter: kunstkernewek
      author: Oliver Scott
      categories:
      - releases   
    _posts/projects: |
      published: false
      layout: article
      title: Your Post Title
      abstract: Short summary of your article.
      author_twitter: kunstkernewek
      author: Oliver Scott
      categories:
      - projects